# This is a basic workflow to help you get started with Actions

name: Manual-input-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      1name:
        description: "Repository URL"
        required: true
      2name: 
        description: "Branch name"
        required: true
      3name:
        type: choice
        description: "Option to print a file"
        required: true
        options: 
        - world
        - welcome
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node and run node application
        uses: actions/setup-node@v3
        
      - name: run node app
        run: node index.js
          
      - name: To print node and npm version
        run: |
            node -v
            npm -v
            
      - name: list all docker images
        run: sudo docker images
        
      - name: to print version of docker 
        run: docker -v
        
      - name: to print version of docker compose
        run: docker compose version
        
      - name: to upload an artifact
        run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
          
      - run: echo welcome to Numocity > path/to/artifact/welcome.txt
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/welcome.txt
          
      - name: Download artifact
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: https://github.com/nischitha24/gitactions/suites/7848995300/artifacts/332377131
     
